include ':app'
include ':rudolph-compiler'
include ':rudolph-annotations'
include ':rudolph'
include ':sampleA'
include ':sampleA-protocol'
include ':sampleB'
include ':sampleB-protocol'

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }
    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
    dependencies {
        classpath "cn.wzbos.android:chihiro-plugin:$CHIHIRO_PLUGIN_VERSION"
    }
}
apply plugin: 'chihiro-settings'