CHIHIRO_GROUP_ID=cn.wzbos.android
CHIHIRO_ARTIFACT_ID=rudolph-compiler
# 版本在工程级的 gradle.properties 统一设置
CHIHIRO_VERSION=2.2.2
CHIHIRO_POM_NAME=rudolph-annotations
CHIHIRO_POM_DESCRIPTION=The compiler used in rudolph
CHIHIRO_POM_URL=https\://github.com/wzbos/Android-Rudolph-Router
CHIHIRO_POM_INCEPTION_YEAR=2019
CHIHIRO_POM_LICENSE_NAME=The Apache Software License, Version 2.0
CHIHIRO_POM_LICENSE_URL=https\://www.apache.org/licenses/LICENSE-2.0.txt
CHIHIRO_POM_DEVELOPER_ID=wzbos
CHIHIRO_POM_DEVELOPER_NAME=wuzongbo
CHIHIRO_POM_DEVELOPER_EMAIL=sckoo@163.com
CHIHIRO_POM_SCM_CONNECTION=scm\:git\:https\://github.com/wzbos/Android-Rudolph-Router.git
CHIHIRO_POM_SCM_DEVELOPER_CONNECTION=scm\:git\:ssh\://github.com/wzbos/Android-Rudolph-Router.git
CHIHIRO_POM_SCM_URL=https\://github.com/wzbos/Android-Rudolph-Router
CHIHIRO_ENABLE_JRELEASER=false